"""Adwaita tint: palette-driven GTK without a separate theme (Omarchy-style).

libadwaita apps load ``~/.config/gtk-4.0/gtk.css`` after the theme
stylesheet, so overriding the named Adwaita palette colors there tints every
GTK4 application while stock Adwaita keeps providing the widgets. GTK3
Adwaita gets the equivalent treatment through ``theme_*`` overrides in
``~/.config/gtk-3.0/gtk.css``. Combined with gsettings gtk-theme
"Adwaita-dark", this removes the need for the vendored FlatColor theme on
standalone window managers.

Files rewritten here carry MARKER; pre-existing unmarked user CSS is backed
up once to ``<name>.pre-wallpaperctl`` before the first overwrite.
"""

from __future__ import annotations

from pathlib import Path

from wallpaperctl.theme.cosmic import pick_accent
from wallpaperctl.util import hex_to_rgb, home

MARKER = (
    "/* Generated by wallpaperctl (Adwaita tint from the active wallpaper "
    "palette). */"
)
BACKUP_SUFFIX = ".pre-wallpaperctl"

BLACK = "#000000"
WHITE = "#FFFFFF"


def _ensure_hash(c: str) -> str:
    c = (c or "").strip()
    if not c:
        return ""
    if not c.startswith("#"):
        c = f"#{c}"
    return c.lower()


def _luma(c: str) -> float:
    try:
        r, g, b = hex_to_rgb(c)
    except ValueError:
        return 0.0
    return (0.299 * r + 0.587 * g + 0.114 * b) / 255.0


def _mix(start: str, end: str, amount: float) -> str:
    try:
        sr, sg, sb = hex_to_rgb(start)
        er, eg, eb = hex_to_rgb(end)
    except ValueError:
        return _ensure_hash(start) or BLACK
    amount = max(0.0, min(1.0, amount))
    mixed = (
        round(sr * (1 - amount) + er * amount),
        round(sg * (1 - amount) + eg * amount),
        round(sb * (1 - amount) + eb * amount),
    )
    return f"#{mixed[0]:02x}{mixed[1]:02x}{mixed[2]:02x}"


def build_adwaita_css(
    colors: dict,
    *,
    accent_strategy: str = "warmest",
) -> tuple[str, str]:
    """Return (gtk4_css, gtk3_css) for a pywal-format palette."""
    special = colors.get("special") or {}
    ansi = colors.get("colors") or {}

    def ansi_hex(i: int) -> str:
        return _ensure_hash(str(ansi.get(f"color{i}", "")))

    bg = _ensure_hash(str(special.get("background", ""))) or ansi_hex(0) or "#101010"
    fg = _ensure_hash(str(special.get("foreground", ""))) or ansi_hex(15) or "#cccccc"
    palette16 = [ansi_hex(i) or bg for i in range(16)]
    muted = palette16[8] or _mix(bg, fg, 0.45)
    accent, accent_soft = pick_accent(palette16, strategy=accent_strategy)
    # pick_accent resolves via color_at_line, which uppercases.
    accent = _ensure_hash(accent)
    accent_soft = _ensure_hash(accent_soft)
    on_accent = BLACK if _luma(accent) > 0.55 else WHITE

    # Terminal-palette block (keeps gtk4 consumers like ghostty working).
    palette_lines = [
        f"@define-color color{i} {palette16[i]};" for i in range(16)
    ] + [
        "@define-color bg_color @color0;",
        "@define-color fg_color @color15;",
        "@define-color selected_bg_color mix(@color0, @color15, 0.12);",
        f"@define-color muted_fg_color {muted};",
        f"@define-color border_color {_mix(bg, fg, 0.08)};",
    ]

    # libadwaita named colors (theme stylesheet names, overridden in user CSS).
    adwaita_lines = [
        f"@define-color accent_color {accent};",
        f"@define-color accent_bg_color {accent};",
        f"@define-color accent_fg_color {on_accent};",
        f"@define-color window_bg_color {bg};",
        f"@define-color window_fg_color {fg};",
        f"@define-color view_bg_color {bg};",
        f"@define-color view_fg_color {fg};",
        f"@define-color headerbar_bg_color {accent_soft};",
        f"@define-color headerbar_fg_color {fg};",
        f"@define-color headerbar_backdrop_color {bg};",
        f"@define-color card_bg_color {_mix(bg, fg, 0.05)};",
        f"@define-color card_fg_color {fg};",
        f"@define-color sidebar_bg_color {_mix(bg, fg, 0.03)};",
        f"@define-color sidebar_fg_color {fg};",
        f"@define-color sidebar_backdrop_color {bg};",
        f"@define-color popover_bg_color {_mix(bg, fg, 0.07)};",
        f"@define-color popover_fg_color {fg};",
        f"@define-color dialog_bg_color {_mix(bg, fg, 0.07)};",
        f"@define-color dialog_fg_color {fg};",
        "@define-color shade_color rgba(0, 0, 0, 0.36);",
        "@define-color scrollbar_outline_color rgba(0, 0, 0, 0.5);",
    ]

    gtk4_css = "\n".join(
        [MARKER, "", "/* Terminal palette */", *palette_lines, ""]
        + ["/* libadwaita palette */", *adwaita_lines, ""]
    )

    gtk3_css = "\n".join(
        [
            MARKER,
            "",
            f"@define-color bg_color {bg};",
            f"@define-color fg_color {fg};",
            f"@define-color base_color {bg};",
            f"@define-color text_color {fg};",
            f"@define-color selected_bg_color {accent};",
            f"@define-color selected_fg_color {on_accent};",
            f"@define-color theme_bg_color {bg};",
            f"@define-color theme_fg_color {fg};",
            f"@define-color theme_base_color {bg};",
            f"@define-color theme_text_color {fg};",
            f"@define-color theme_selected_bg_color {accent};",
            f"@define-color theme_selected_fg_color {on_accent};",
            f"@define-color theme_tooltip_bg_color {_mix(bg, BLACK, 0.25)};",
            f"@define-color theme_tooltip_fg_color {fg};",
            f"@define-color borders {_mix(bg, fg, 0.18)};",
            f"@define-color insensitive_bg_color {_mix(bg, fg, 0.06)};",
            f"@define-color insensitive_fg_color {_mix(fg, bg, 0.45)};",
            f"@define-color wm_border {_mix(bg, fg, 0.18)};",
            "",
        ]
    )
    return gtk4_css, gtk3_css


def write_adwaita_css(
    gtk4_css: str,
    gtk3_css: str,
    *,
    base_dir: Path | None = None,
) -> list[Path]:
    """Write user gtk.css files; back up unmarked originals once."""
    base = base_dir if base_dir is not None else home() / ".config"
    written: list[Path] = []
    for rel, content in (
        ("gtk-4.0/gtk.css", gtk4_css),
        ("gtk-3.0/gtk.css", gtk3_css),
    ):
        path = base / rel
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            if path.is_file():
                text = path.read_text(encoding="utf-8", errors="replace")
                if MARKER not in text:
                    backup = path.parent / (path.name + BACKUP_SUFFIX)
                    if not backup.exists():
                        backup.write_text(text, encoding="utf-8")
            path.write_text(content, encoding="utf-8")
        except OSError:
            continue
        written.append(path)
    return written
