"""Omarchy dynamic theme operation.

Maps the wallust palette (~/.cache/wal/colors.json) onto the persistent
"Dynamic Wallpapers" Omarchy theme (colors.toml), keeps the theme's
backgrounds/ and wallpaper-video staging in sync with the active wallpaper,
then re-applies the theme through official tooling (`omarchy theme refresh`)
so every Omarchy-managed app gets retinted from templates.

The op is inert unless the dynamic theme is the active Omarchy theme; in that
case it never creates new themes — only updates colors within the one theme.
"""

from __future__ import annotations

import logging
import os
import shutil
from pathlib import Path

from wallpaperctl.context import WallpaperContext
from wallpaperctl.omarchy import (
    MOTION_VIDEO_EXTENSIONS,
    THEME_SLUG,
    is_dynamic_theme_active,
    omarchy_available,
    run_omarchy,
    user_theme_dir,
)
from wallpaperctl.theme.base import debug_op
from wallpaperctl.theme.cosmic import pick_accent
from wallpaperctl.theme.pywalfox import load_colors_json
from wallpaperctl.util import have, hex_to_rgb, home, run

log = logging.getLogger("wallpaperctl")

GENERATED_HEADER = (
    "# Generated by wallpaperctl from the active wallpaper palette (wallust).\n"
    "# Do not edit: this file is rewritten on every wallpaper change while the\n"
    "# Dynamic Wallpapers theme is active.\n"
)

BLACK = "#000000"
WHITE = "#FFFFFF"


def _ensure_hash(c: str) -> str:
    c = (c or "").strip()
    if not c:
        return ""
    if not c.startswith("#"):
        c = f"#{c}"
    return c.lower() if len(c) == 7 else c


def _luma(c: str) -> float:
    try:
        r, g, b = hex_to_rgb(c)
    except ValueError:
        return 0.0
    return (r + g + b) / (3 * 255)


def _mix_hex(start: str, end: str, amount: float) -> str:
    """Blend two hex colors; amount 0.0 = start, 1.0 = end."""
    try:
        sr, sg, sb = hex_to_rgb(start)
        er, eg, eb = hex_to_rgb(end)
    except ValueError:
        return _ensure_hash(start) or BLACK
    amount = max(0.0, min(1.0, amount))
    mixed = (
        round(sr * (1 - amount) + er * amount),
        round(sg * (1 - amount) + eg * amount),
        round(sb * (1 - amount) + eb * amount),
    )
    return "#{:02x}{:02x}{:02x}".format(*mixed)


def build_colors_mapping(
    colors: dict,
    *,
    accent_strategy: str = "warmest",
) -> dict[str, str]:
    """Translate a pywal-format palette into Omarchy semantic colors.toml keys.

    Omarchy's omarchy-theme-color derives most keys itself, but ``accent`` has
    no derivation, so it must always be emitted (charset-safe values only).
    """
    special = colors.get("special") or {}
    ansi = colors.get("colors") or {}

    def ansi_hex(i: int) -> str:
        return _ensure_hash(str(ansi.get(f"color{i}", "")))

    bg = _ensure_hash(str(special.get("background", ""))) or ansi_hex(0) or "#101010"
    fg = _ensure_hash(str(special.get("foreground", ""))) or ansi_hex(7) or "#cccccc"

    palette16 = [ansi_hex(i) or bg for i in range(16)]
    raw_accent, _soft = pick_accent(palette16, strategy=accent_strategy)
    accent = _ensure_hash(raw_accent) or palette16[4]

    accent_alt = _mix_hex(accent, fg, 0.35)
    orange = _mix_hex(palette16[1], palette16[3], 0.5)

    mapping: dict[str, str] = {}
    mapping["mode"] = "light" if _luma(bg) > 0.5 else "dark"
    mapping["accent"] = accent
    mapping["selection"] = _mix_hex(bg, accent, 0.25)
    mapping["muted"] = palette16[8]

    mapping["background"] = bg
    mapping["dark_background"] = _mix_hex(bg, BLACK, 0.25)
    mapping["darker_background"] = _mix_hex(bg, BLACK, 0.50)
    mapping["lighter_background"] = _mix_hex(bg, WHITE, 0.12)

    mapping["foreground"] = fg
    mapping["dark_foreground"] = palette16[8]
    mapping["light_foreground"] = palette16[7]
    mapping["bright_foreground"] = palette16[15]

    mapping["red"] = palette16[1]
    mapping["green"] = palette16[2]
    mapping["yellow"] = palette16[3]
    mapping["blue"] = palette16[4]
    mapping["magenta"] = palette16[5]
    mapping["cyan"] = palette16[6]
    mapping["orange"] = orange
    mapping["brown"] = _mix_hex(orange, BLACK, 0.5)

    for name, idx in (
        ("bright_red", 9),
        ("bright_green", 10),
        ("bright_yellow", 11),
        ("bright_blue", 12),
        ("bright_magenta", 13),
        ("bright_cyan", 14),
    ):
        mapping[name] = palette16[idx]

    for i in range(16):
        mapping[f"color{i}"] = palette16[i]

    mapping["cursor"] = palette16[15]
    mapping["hyprland_active_border"] = (
        f"rgba({accent.lstrip('#')}ee) rgba({accent_alt.lstrip('#')}ee) 45deg"
    )
    return mapping


def render_colors_toml(mapping: dict[str, str]) -> str:
    lines = [GENERATED_HEADER.rstrip("\n"), ""]
    for key, value in mapping.items():
        lines.append(f'{key} = "{value}"')
    return "\n".join(lines) + "\n"


def write_colors_toml(theme_dir: Path, mapping: dict[str, str]) -> Path:
    theme_dir.mkdir(parents=True, exist_ok=True)
    target = theme_dir / "colors.toml"
    tmp = target.with_suffix(".toml.tmp")
    tmp.write_text(render_colors_toml(mapping), encoding="utf-8")
    os.replace(tmp, target)
    return target


def _hardlink_or_copy(src: Path, dst: Path) -> bool:
    try:
        if dst.exists() or dst.is_symlink():
            dst.unlink()
        os.link(src, dst)
        return True
    except OSError:
        try:
            shutil.copy2(src, dst)
            return True
        except OSError as e:
            log.debug("omarchy theme: failed to stage %s → %s: %s", src, dst, e)
            return False


def sync_theme_media(
    theme_dir: Path,
    image_path: Path,
    *,
    video_path: Path | None = None,
) -> bool:
    """Keep backgrounds/, preview.png and wallpaper-video staging in sync.

    backgrounds/ holds exactly the active (still) image so re-selecting the
    theme in the switcher restores the current wallpaper. wallpaper-video.<ext>
    makes the stock motion-wallpaper theme-set hook play/stop the video.
    """
    ok = True
    backgrounds = theme_dir / "backgrounds"
    backgrounds.mkdir(parents=True, exist_ok=True)

    for entry in backgrounds.iterdir():
        try:
            if entry.is_file() or entry.is_symlink():
                entry.unlink()
        except OSError as e:
            log.debug("omarchy theme: could not clear %s: %s", entry, e)

    if image_path.is_file():
        ok = _hardlink_or_copy(image_path.resolve(), backgrounds / image_path.name)

    for entry in theme_dir.glob("wallpaper-video.*"):
        try:
            entry.unlink()
        except OSError as e:
            log.debug("omarchy theme: could not remove %s: %s", entry, e)
    if video_path is not None and video_path.is_file():
        suffix = video_path.suffix.lstrip(".").lower()
        if suffix in MOTION_VIDEO_EXTENSIONS:
            staged = _hardlink_or_copy(
                video_path, theme_dir / f"wallpaper-video.{suffix}"
            )
            ok = ok and staged
        else:
            log.debug(
                "omarchy theme: video codec %s not stageable; playback stays setter-driven",
                suffix,
            )

    _write_preview(theme_dir, image_path)
    return ok


def _write_preview(theme_dir: Path, image_path: Path) -> None:
    try:
        from PIL import Image

        with Image.open(image_path) as img:
            img = img.convert("RGB")
            img.thumbnail((480, 480))
            img.save(theme_dir / "preview.png", format="PNG")
    except Exception as e:  # noqa: BLE001 — preview is best-effort
        log.debug("omarchy theme: preview generation failed: %s", e)


def write_palette_preview(theme_dir: Path, mapping: dict[str, str]) -> bool:
    """Render a palette swatch preview.png (switcher hides themes without one)."""
    try:
        from PIL import Image

        swatches = [
            mapping.get("background", "#101010"),
            mapping.get("accent", "#888888"),
            mapping.get("foreground", "#cccccc"),
            mapping.get("selection", "#333333"),
            mapping.get("red", "#cc6666"),
            mapping.get("green", "#99cc99"),
            mapping.get("yellow", "#e0c060"),
            mapping.get("blue", "#6699cc"),
            mapping.get("magenta", "#cc99cc"),
            mapping.get("cyan", "#66cccc"),
        ]
        width, height = 480, 270
        band = height // len(swatches)
        img = Image.new("RGB", (width, height))
        for i, color in enumerate(swatches):
            try:
                rgb = hex_to_rgb(color)
            except ValueError:
                rgb = (128, 128, 128)
            band_img = Image.new("RGB", (width, band), rgb)
            img.paste(band_img, (0, i * band))
        img.save(theme_dir / "preview.png", format="PNG")
        return True
    except Exception as e:  # noqa: BLE001 — preview is best-effort
        log.debug("omarchy theme: palette preview generation failed: %s", e)
        return False


class OmarchyThemeOp:
    name = "omarchy"

    def enabled(self, ctx: WallpaperContext) -> bool:
        if not ctx.ops.enable_omarchy:
            return False
        if not omarchy_available():
            return False
        return is_dynamic_theme_active(
            getattr(ctx.ops, "omarchy_theme_slug", THEME_SLUG)
        )

    def _heal_opencode(self, ctx: WallpaperContext) -> None:
        """Undo any stray wallust opencode theming (belt and braces).

        Long-running opencode sessions can still carry the removed
        wallust-hot-reload plugin, and older wallust configs had a hook that
        flipped tui.json back to theme "wallust" on every wallust run. Fix
        the registration whenever a wallpaper change touches the theme.
        """
        try:
            tui_path = home() / ".config" / "opencode" / "tui.json"
            if not tui_path.is_file():
                return
            import json

            tui = json.loads(tui_path.read_text(encoding="utf-8"))
            if not isinstance(tui, dict):
                return
            plugins = tui.get("plugin")
            listed = isinstance(plugins, list) and any(
                "wallust-hot-reload" in str(p) for p in plugins
            )
            if tui.get("theme") != "wallust" and not listed:
                return
        except (OSError, ValueError):
            return

        from wallpaperctl.setup.opencode_bootstrap import remove_opencode_plugin

        debug_op(self.name, "healing stray wallust opencode theming", ctx)
        remove_opencode_plugin()
        for stale in (
            home() / ".config" / "opencode" / "themes" / "wallust.json",
            *sorted((home() / ".config" / "opencode" / "themes").glob("wallust-hot-*.json")),
        ):
            try:
                stale.unlink()
            except OSError:
                pass

    def run(self, ctx: WallpaperContext) -> bool:
        slug = getattr(ctx.ops, "omarchy_theme_slug", THEME_SLUG)
        theme_dir = user_theme_dir(slug)
        debug_op(self.name, f"updating dynamic theme at {theme_dir}", ctx)

        colors = load_colors_json()
        if not colors:
            debug_op(self.name, "no ~/.cache/wal/colors.json (wallust op failed?)", ctx)
            return False

        strategy = (
            getattr(ctx.ops, "omarchy_accent_strategy", None)
            or getattr(ctx.ops, "rgb_color_strategy", "warmest")
            or "warmest"
        )
        mapping = build_colors_mapping(colors, accent_strategy=strategy)
        rendered = render_colors_toml(mapping)
        colors_file = theme_dir / "colors.toml"
        previous = _read_text(colors_file)
        write_colors_toml(theme_dir, mapping)
        debug_op(self.name, f"wrote {colors_file}", ctx)

        image = ctx.image_path
        if image is None or not image.is_file():
            debug_op(self.name, "no still image for theme media sync", ctx)
            return False
        sync_theme_media(
            theme_dir,
            image,
            video_path=ctx.path if ctx.is_animated else None,
        )

        self._heal_opencode(ctx)

        if not getattr(ctx.ops, "omarchy_refresh_apps", True):
            debug_op(
                self.name,
                "omarchy_refresh_apps disabled: colors.toml staged only "
                "(applied on next theme set/refresh)",
                ctx,
            )
            return True

        # Palette unchanged (e.g. -R reload of the same wallpaper): skip the
        # app-retint churn — it restarts terminals/WM config and interrupts
        # running TUI agents (known Omarchy upstream annoyance).
        if (
            getattr(ctx.ops, "omarchy_skip_unchanged", True)
            and previous is not None
            and previous == rendered
        ):
            debug_op(self.name, "palette unchanged; skipping theme refresh", ctx)
            return True

        timeout = float(getattr(ctx.ops, "omarchy_timeout", 60))
        r = run_omarchy(["theme", "refresh"], timeout=timeout)
        if r.returncode != 0:
            debug_op(
                self.name,
                f"omarchy theme refresh failed (rc={r.returncode}), trying theme set",
                ctx,
            )
            r = run_omarchy(
                ["theme", "set", slug],
                timeout=timeout,
                env_extra={"OMARCHY_THEME_SKIP_BACKGROUND": "1"},
            )
        if r.returncode != 0:
            debug_op(
                self.name,
                f"omarchy theme set failed: {(r.stderr or r.stdout or '')[:200]}",
                ctx,
            )
            return False

        # opencode sessions reload themes on SIGUSR2. The omarchy-theme TUI
        # plugin watches omarchy.json for a no-interruption retint, but the
        # watcher misses events in some setups (observed under kitty reloads
        # racing the theme-set post commands), leaving sessions one palette
        # behind. Nudge every running opencode so the fresh palette lands.
        self._publish_opencode_theme(ctx)
        self._signal_opencode(ctx)
        # Restore the stable default for FUTURE sessions: running ones have
        # already resolved the hashed theme above, and new sessions starting
        # with "omarchy" read the current omarchy.json (fresh palette) at
        # startup — so the picker doesn't stay parked on a hash name.
        self._reset_opencode_theme_default(ctx)
        debug_op(self.name, "theme refreshed via omarchy", ctx)
        return True

    def _publish_opencode_theme(self, ctx: WallpaperContext) -> None:
        """Install the live omarchy.json under its content-hashed theme name.

        opencode caches theme content by NAME: re-reading the same theme name
        (plain SIGUSR2 reload of "omarchy") keeps the stale registry entry, so
        a changed omarchy.json never reaches sessions that missed the TUI
        plugin's file event. Writing the content under omarchy-<hash>.json and
        selecting that name in tui.json forces a fresh resolve on reload — the
        same trick omarchy's own plugin uses, with the same FNV-1a hash so the
        plugin's prune logic treats our file as its own.
        """
        import json as json_mod

        themes_dir = home() / ".config" / "opencode" / "themes"
        live = themes_dir / "omarchy.json"
        if not live.is_file():
            return
        try:
            text = live.read_text(encoding="utf-8")
            json_mod.loads(text)
        except (OSError, ValueError):
            return

        name = f"omarchy-{_fnv1a8(text)}"
        target = themes_dir / f"{name}.json"
        if not target.is_file():
            try:
                target.write_text(text, encoding="utf-8")
            except OSError as e:
                debug_op(self.name, f"could not stage {target}: {e}", ctx)
                return

        # Keep the last few hashed themes: a running session may still be
        # SELECTED on an older one, and deleting its file makes the theme
        # unresolvable on SIGUSR2 reloads (session falls back and looks
        # stuck until manually re-selected). The omarchy plugin prunes again
        # after its own successful applies.
        hashed = sorted(
            (p for p in themes_dir.glob("omarchy-*.json") if p != target),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        for stale in hashed[2:]:
            try:
                stale.unlink()
            except OSError:
                pass

        tui_path = home() / ".config" / "opencode" / "tui.json"
        try:
            if tui_path.is_file():
                tui = json_mod.loads(tui_path.read_text(encoding="utf-8"))
                if not isinstance(tui, dict):
                    tui = {}
            else:
                tui = {"$schema": "https://opencode.ai/tui.json"}
        except (OSError, ValueError):
            return
        if tui.get("theme") == name:
            return
        tui["theme"] = name
        try:
            tmp = tui_path.with_name(".tui.json.tmp")
            tmp.write_text(json_mod.dumps(tui, indent=2) + "\n", encoding="utf-8")
            os.replace(tmp, tui_path)
        except OSError as e:
            debug_op(self.name, f"could not update tui.json: {e}", ctx)
            return
        debug_op(self.name, f"opencode theme → {name}", ctx)

    def _signal_opencode(self, ctx: WallpaperContext) -> None:
        if have("omarchy-restart-opencode"):
            r = run(["omarchy-restart-opencode"], timeout=10)
        elif have("pkill"):
            r = run(["pkill", "-USR2", "-x", "opencode"], timeout=5)
        else:
            debug_op(self.name, "no pkill/omarchy-restart-opencode; skipping signal", ctx)
            return
        debug_op(
            self.name,
            f"SIGUSR2 → opencode (rc={r.returncode})",
            ctx,
        )

    def _reset_opencode_theme_default(self, ctx: WallpaperContext) -> None:
        """Point tui.json back at the stable "omarchy" theme for future sessions.

        Running sessions already resolved the hashed theme published above and
        keep following via the plugin; tui.json is only read on (re)start, and
        "omarchy" always maps to the current omarchy.json content.
        """
        import json as json_mod
        import time

        time.sleep(2)  # let SIGUSR2 reloads finish before touching tui.json
        tui_path = home() / ".config" / "opencode" / "tui.json"
        try:
            tui = json_mod.loads(tui_path.read_text(encoding="utf-8"))
            if not isinstance(tui, dict) or tui.get("theme") == "omarchy":
                return
            tui["theme"] = "omarchy"
            tmp = tui_path.with_name(".tui.json.tmp")
            tmp.write_text(json_mod.dumps(tui, indent=2) + "\n", encoding="utf-8")
            os.replace(tmp, tui_path)
            debug_op(self.name, "tui.json theme reset to 'omarchy' for future sessions", ctx)
        except (OSError, ValueError) as e:
            debug_op(self.name, f"could not reset tui.json theme: {e}", ctx)


def _read_text(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return None


def _fnv1a8(text: str) -> str:
    """FNV-1a 32-bit, hex-8 — mirrors omarchy-theme.ts's contentHash()."""
    h = 0x811C9DC5
    for ch in text:
        h ^= ord(ch)
        h = (h * 0x01000193) & 0xFFFFFFFF
    return f"{h:08x}"


def fallback_palette() -> dict:
    """Neutral dark palette for first-time bootstrap before any wallust run."""
    return {
        "special": {
            "background": "#101418",
            "foreground": "#c8ccd4",
            "cursor": "#c8ccd4",
        },
        "colors": {
            "color0": "#101418",
            "color1": "#cc6666",
            "color2": "#b5bd68",
            "color3": "#f0c674",
            "color4": "#81a2be",
            "color5": "#b294bb",
            "color6": "#8abeb7",
            "color7": "#c8ccd4",
            "color8": "#5c6370",
            "color9": "#de6e5c",
            "color10": "#98c379",
            "color11": "#e5c07b",
            "color12": "#61afef",
            "color13": "#c678dd",
            "color14": "#56b6c2",
            "color15": "#e6e6e6",
        },
    }


def ensure_theme_skeleton(
    theme_dir: Path | None = None,
    *,
    accent_strategy: str = "warmest",
) -> bool:
    """Create the dynamic theme skeleton if it does not exist yet (setup path)."""
    theme_dir = theme_dir or user_theme_dir()
    colors_file = theme_dir / "colors.toml"
    if colors_file.is_file():
        return False

    colors = load_colors_json()
    if not colors:
        wal_colors = home() / ".cache" / "wal" / "colors"
        if wal_colors.is_file():
            lines = [
                line.strip()
                for line in wal_colors.read_text(encoding="utf-8", errors="replace").splitlines()
                if line.strip()
            ]
            if len(lines) >= 16:
                colors = {
                    "special": {
                        "background": lines[0],
                        "foreground": lines[7],
                        "cursor": lines[15],
                    },
                    "colors": {f"color{i}": lines[i] for i in range(16)},
                }
    if not colors:
        colors = fallback_palette()

    write_colors_toml(theme_dir, build_colors_mapping(colors, accent_strategy=accent_strategy))
    (theme_dir / "backgrounds").mkdir(parents=True, exist_ok=True)

    current = home() / ".wallpaper"
    seeded = False
    try:
        if current.is_file():
            wallpaper = Path(current.read_text(encoding="utf-8").strip())
            if wallpaper.is_file():
                sync_theme_media(theme_dir, wallpaper)
                seeded = True
    except OSError as e:
        log.debug("omarchy theme: could not seed backgrounds: %s", e)

    # The omarchy theme switcher only lists themes that ship a preview image.
    if not seeded and not (theme_dir / "preview.png").is_file():
        mapping = build_colors_mapping(colors, accent_strategy=accent_strategy)
        write_palette_preview(theme_dir, mapping)
    return True
