"""Omarchy dynamic theme operation.

Maps the wallust palette onto the persistent "Dynamic Wallpapers" theme
(colors.toml), keeps backgrounds/ and wallpaper-video staging in sync, then
retints the running session the same way a video-capable Omarchy theme does:
live shell palette, Kitty SIGUSR1, Hyprland border ``keyword``s — then has
``omarchy-theme-set-browser`` re-tint Chromium-family browser chrome from the
regenerated theme (omarchy theme set would do the same on a full switch).

Wallpaper changes are not theme switches. Do not run ``omarchy theme set`` /
``theme refresh`` (that ``hyprctl reload``s and snaps autorotation). Screen
rotate rebinding stays in ``omarchy_watch``.

The op is inert unless the dynamic theme is already active.
"""

from __future__ import annotations

import logging
import os
import re
import shutil
import time
from pathlib import Path

from wallpaperctl.context import WallpaperContext
from wallpaperctl.omarchy import (
    MOTION_VIDEO_EXTENSIONS,
    THEME_SLUG,
    apply_shell_theme_live,
    is_dynamic_theme_active,
    omarchy_available,
    omarchy_env,
    user_theme_dir,
)
from wallpaperctl.theme.base import debug_op
from wallpaperctl.theme.cosmic import pick_accent
from wallpaperctl.theme.pywalfox import load_colors_json
from wallpaperctl.util import have, hex_to_rgb, home, pgrep_exact, run

log = logging.getLogger("wallpaperctl")

GENERATED_HEADER = (
    "# Generated by wallpaperctl from the active wallpaper palette (wallust).\n"
    "# Do not edit: this file is rewritten on every wallpaper change while the\n"
    "# Dynamic Wallpapers theme is active.\n"
)

BLACK = "#000000"
WHITE = "#FFFFFF"


def _ensure_hash(c: str) -> str:
    c = (c or "").strip()
    if not c:
        return ""
    if not c.startswith("#"):
        c = f"#{c}"
    return c.lower() if len(c) == 7 else c


def _luma(c: str) -> float:
    try:
        r, g, b = hex_to_rgb(c)
    except ValueError:
        return 0.0
    return (r + g + b) / (3 * 255)


def _mix_hex(start: str, end: str, amount: float) -> str:
    """Blend two hex colors; amount 0.0 = start, 1.0 = end."""
    try:
        sr, sg, sb = hex_to_rgb(start)
        er, eg, eb = hex_to_rgb(end)
    except ValueError:
        return _ensure_hash(start) or BLACK
    amount = max(0.0, min(1.0, amount))
    mixed = (
        round(sr * (1 - amount) + er * amount),
        round(sg * (1 - amount) + eg * amount),
        round(sb * (1 - amount) + eb * amount),
    )
    return "#{:02x}{:02x}{:02x}".format(*mixed)


def build_colors_mapping(
    colors: dict,
    *,
    accent_strategy: str = "warmest",
) -> dict[str, str]:
    """Translate a pywal-format palette into Omarchy semantic colors.toml keys.

    Omarchy's omarchy-theme-color derives most keys itself, but ``accent`` has
    no derivation, so it must always be emitted (charset-safe values only).
    """
    special = colors.get("special") or {}
    ansi = colors.get("colors") or {}

    def ansi_hex(i: int) -> str:
        return _ensure_hash(str(ansi.get(f"color{i}", "")))

    bg = _ensure_hash(str(special.get("background", ""))) or ansi_hex(0) or "#101010"
    fg = _ensure_hash(str(special.get("foreground", ""))) or ansi_hex(7) or "#cccccc"

    palette16 = [ansi_hex(i) or bg for i in range(16)]
    raw_accent, _soft = pick_accent(palette16, strategy=accent_strategy)
    accent = _ensure_hash(raw_accent) or palette16[4]

    accent_alt = _mix_hex(accent, fg, 0.35)
    orange = _mix_hex(palette16[1], palette16[3], 0.5)

    mapping: dict[str, str] = {}
    mapping["mode"] = "light" if _luma(bg) > 0.5 else "dark"
    mapping["accent"] = accent
    mapping["selection"] = _mix_hex(bg, accent, 0.25)
    mapping["muted"] = palette16[8]

    mapping["background"] = bg
    mapping["dark_background"] = _mix_hex(bg, BLACK, 0.25)
    mapping["darker_background"] = _mix_hex(bg, BLACK, 0.50)
    mapping["lighter_background"] = _mix_hex(bg, WHITE, 0.12)

    mapping["foreground"] = fg
    mapping["dark_foreground"] = palette16[8]
    mapping["light_foreground"] = palette16[7]
    mapping["bright_foreground"] = palette16[15]

    mapping["red"] = palette16[1]
    mapping["green"] = palette16[2]
    mapping["yellow"] = palette16[3]
    mapping["blue"] = palette16[4]
    mapping["magenta"] = palette16[5]
    mapping["cyan"] = palette16[6]
    mapping["orange"] = orange
    mapping["brown"] = _mix_hex(orange, BLACK, 0.5)

    for name, idx in (
        ("bright_red", 9),
        ("bright_green", 10),
        ("bright_yellow", 11),
        ("bright_blue", 12),
        ("bright_magenta", 13),
        ("bright_cyan", 14),
    ):
        mapping[name] = palette16[idx]

    for i in range(16):
        mapping[f"color{i}"] = palette16[i]

    mapping["cursor"] = palette16[15]
    mapping["hyprland_active_border"] = (
        f"rgba({accent.lstrip('#')}ee) rgba({accent_alt.lstrip('#')}ee) 45deg"
    )
    return mapping


def render_colors_toml(mapping: dict[str, str]) -> str:
    lines = [GENERATED_HEADER.rstrip("\n"), ""]
    for key, value in mapping.items():
        lines.append(f'{key} = "{value}"')
    return "\n".join(lines) + "\n"


def write_colors_toml(theme_dir: Path, mapping: dict[str, str]) -> Path:
    theme_dir.mkdir(parents=True, exist_ok=True)
    target = theme_dir / "colors.toml"
    tmp = target.with_suffix(".toml.tmp")
    tmp.write_text(render_colors_toml(mapping), encoding="utf-8")
    os.replace(tmp, target)
    return target


def _hardlink_or_copy(src: Path, dst: Path) -> bool:
    try:
        if dst.exists() or dst.is_symlink():
            dst.unlink()
        os.link(src, dst)
        return True
    except OSError:
        try:
            shutil.copy2(src, dst)
            return True
        except OSError as e:
            log.debug("omarchy theme: failed to stage %s → %s: %s", src, dst, e)
            return False


def sync_theme_media(
    theme_dir: Path,
    image_path: Path,
    *,
    video_path: Path | None = None,
) -> bool:
    """Keep backgrounds/, preview.png and wallpaper-video staging in sync.

    backgrounds/ holds exactly the active (still) image so re-selecting the
    theme in the switcher restores the current wallpaper. wallpaper-video.<ext>
    is what the wallpaperctl theme-set hook plays (or stops, when absent).
    """
    ok = True
    backgrounds = theme_dir / "backgrounds"
    backgrounds.mkdir(parents=True, exist_ok=True)

    for entry in backgrounds.iterdir():
        try:
            if entry.is_file() or entry.is_symlink():
                entry.unlink()
        except OSError as e:
            log.debug("omarchy theme: could not clear %s: %s", entry, e)

    if image_path.is_file():
        ok = _hardlink_or_copy(image_path.resolve(), backgrounds / image_path.name)

    for entry in theme_dir.glob("wallpaper-video.*"):
        try:
            entry.unlink()
        except OSError as e:
            log.debug("omarchy theme: could not remove %s: %s", entry, e)
    if video_path is not None and video_path.is_file():
        suffix = video_path.suffix.lstrip(".").lower()
        if suffix in MOTION_VIDEO_EXTENSIONS:
            staged = _hardlink_or_copy(
                video_path, theme_dir / f"wallpaper-video.{suffix}"
            )
            ok = ok and staged
        else:
            log.debug(
                "omarchy theme: video codec %s not stageable; playback stays setter-driven",
                suffix,
            )

    _write_preview(theme_dir, image_path)
    return ok


def _write_preview(theme_dir: Path, image_path: Path) -> None:
    try:
        from PIL import Image

        with Image.open(image_path) as img:
            img = img.convert("RGB")
            img.thumbnail((480, 480))
            img.save(theme_dir / "preview.png", format="PNG")
    except Exception as e:  # noqa: BLE001 — preview is best-effort
        log.debug("omarchy theme: preview generation failed: %s", e)


def write_palette_preview(theme_dir: Path, mapping: dict[str, str]) -> bool:
    """Render a palette swatch preview.png (switcher hides themes without one)."""
    try:
        from PIL import Image

        swatches = [
            mapping.get("background", "#101010"),
            mapping.get("accent", "#888888"),
            mapping.get("foreground", "#cccccc"),
            mapping.get("selection", "#333333"),
            mapping.get("red", "#cc6666"),
            mapping.get("green", "#99cc99"),
            mapping.get("yellow", "#e0c060"),
            mapping.get("blue", "#6699cc"),
            mapping.get("magenta", "#cc99cc"),
            mapping.get("cyan", "#66cccc"),
        ]
        width, height = 480, 270
        band = height // len(swatches)
        img = Image.new("RGB", (width, height))
        for i, color in enumerate(swatches):
            try:
                rgb = hex_to_rgb(color)
            except ValueError:
                rgb = (128, 128, 128)
            band_img = Image.new("RGB", (width, band), rgb)
            img.paste(band_img, (0, i * band))
        img.save(theme_dir / "preview.png", format="PNG")
        return True
    except Exception as e:  # noqa: BLE001 — preview is best-effort
        log.debug("omarchy theme: palette preview generation failed: %s", e)
        return False


# Live retint only. Never omarchy-restart-hyprctl / theme-set / theme-refresh:
# those `hyprctl reload` and re-run monitors.lua (autorotation snaps back).
_RETINT_COMMANDS = ("omarchy-restart-terminal",)


def _current_theme_dirs() -> tuple[Path, Path]:
    state = home() / ".local" / "state" / "omarchy" / "current"
    return state / "theme", state / "next-theme"


def _stage_next_theme(theme_dir: Path) -> bool:
    """Put wallust-derived colors.toml where omarchy-theme-set-templates reads.

    Only palette files — not current/theme (stale generated kitty/hyprland)
    and not wallpaper-video (templates do not need the clip).
    """
    _, nxt = _current_theme_dirs()
    colors = theme_dir / "colors.toml"
    if not colors.is_file():
        return False
    try:
        if nxt.exists():
            shutil.rmtree(nxt)
        nxt.mkdir(parents=True)
        shutil.copy2(colors, nxt / "colors.toml")
        shell = theme_dir / "shell.toml"
        if shell.is_file():
            shutil.copy2(shell, nxt / "shell.toml")
        return True
    except OSError as e:
        log.debug("omarchy theme: failed to stage next-theme: %s", e)
        return False


def _install_generated_into_current() -> bool:
    """Copy generated configs over current/theme, never replacing the directory.

    Skip ``*.lua``. Hyprland auto-reloads when ``omarchy.current.theme.hyprland``
    (or ``gum_env``) changes, which re-runs monitors.lua and snaps autorotation
    to the saved laptop profile.
    """
    current, nxt = _current_theme_dirs()
    if not nxt.is_dir():
        return False
    try:
        current.mkdir(parents=True, exist_ok=True)
        for item in nxt.iterdir():
            if item.suffix == ".lua":
                continue
            target = current / item.name
            if item.is_dir():
                if target.exists():
                    shutil.rmtree(target)
                shutil.copytree(item, target, symlinks=True)
            elif item.is_file() or item.is_symlink():
                shutil.copy2(item, target)
        shutil.rmtree(nxt)
        return True
    except OSError as e:
        log.debug("omarchy theme: failed to install generated theme: %s", e)
        return False


_GRADIENT_ANGLE_RE = re.compile(r"^-?\d+(?:\.\d+)?deg$")


def _parse_gradient(spec: str) -> tuple[list[str], str | None]:
    """Split a gradient spec into colors and an optional angle.

    Mirrors ``parse_gradient`` in omarchy-theme-set-templates: whitespace
    separated, parts matching ``<number>deg`` are the angle, the rest are
    colors ("rgba(6e747aee) rgba(788b92ee) 45deg").
    """
    colors: list[str] = []
    angle: str | None = None
    for part in (spec or "").split():
        if _GRADIENT_ANGLE_RE.match(part):
            angle = part[:-3]
        else:
            colors.append(part)
    return colors, angle


def _lua_value(value: object) -> str:
    """Render a Python scalar/list/dict as a hyprlang-lua value."""
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, dict):
        inner = ", ".join(f"{k} = {_lua_value(v)}" for k, v in value.items())
        return f"{{ {inner} }}"
    if isinstance(value, (list, tuple)):
        inner = ", ".join(_lua_value(v) for v in value)
        return f"{{ {inner} }}"
    return str(value)


def _hl_border(spec: str) -> str | dict:
    """Border value in omarchy's ``hypr_gradient`` template form.

    Same rules as ``hypr_gradient_value`` in omarchy-theme-set-templates:
    a single color is a plain string; two or more colors become a
    ``{ colors = { .. }, angle = .. }`` table, with the angle included only
    when the spec carries one.
    """
    colors, angle = _parse_gradient(spec)
    if not colors:
        return spec
    if len(colors) == 1:
        return colors[0]
    if angle is not None:
        try:
            degrees = float(angle)
        except ValueError:
            return {"colors": colors}
        # omarchy writes whole angles as plain integers (angle = 45)
        return {"colors": colors, "angle": int(degrees) if degrees.is_integer() else degrees}
    return {"colors": colors}


def _hl_config_expr(mapping: dict[str, str]) -> str | None:
    """``hl.config({...})`` applying omarchy's border keys, or None.

    Same keys omarchy's generated hyprland.lua writes: general.col and
    group.col border colors. Applied live via ``hyprctl eval`` (the same
    lua API omarchy-hyprland-reload-guard uses) — no compositor reload and
    no hyprland.lua write.
    """
    active = (mapping.get("hyprland_active_border") or "").strip()
    if not active:
        return None
    inactive = (mapping.get("hyprland_inactive_border") or "rgba(595959aa)").strip()
    active_val = _hl_border(active)
    inactive_val = _hl_border(inactive)
    table = _lua_value(
        {
            "general": {
                "col": {
                    "active_border": active_val,
                    "inactive_border": inactive_val,
                },
            },
            "group": {
                "col": {
                    "border_active": active_val,
                    "border_inactive": inactive_val,
                },
            },
        }
    )
    return f"hl.config({table})"


def _apply_hypr_borders(mapping: dict[str, str]) -> None:
    """Live border colors via omarchy's hl.config lua API (``hyprctl eval``).

    ``hyprctl keyword`` cannot parse gradient values on Hyprland 0.56+
    ("keyword can't work with non-legacy parsers"), which left borders on the
    previous theme's colors after every wallpaper change. ``hl.config`` is
    omarchy's own lua config bridge, used the same way by
    omarchy-hyprland-reload-guard; it applies without a compositor reload and
    without writing hyprland.lua.
    """
    if not have("hyprctl"):
        return
    expr = _hl_config_expr(mapping)
    if not expr:
        return
    r = run(["hyprctl", "eval", expr], timeout=5)
    if r.returncode != 0 or "ok" not in (r.stdout or "").lower():
        log.debug(
            "hyprctl eval hl.config failed: %s",
            (r.stderr or r.stdout or "")[:160],
        )


def retint_without_compositor_reload(
    theme_dir: Path,
    slug: str,
    mapping: dict[str, str] | None = None,
) -> bool:
    """Render Kitty (etc.) from wallust colors; retint Hypr borders via hl.config."""
    del slug  # kept so callers stay (theme_dir, slug)
    if not have("omarchy-theme-set-templates"):
        return False
    if not _stage_next_theme(theme_dir):
        return False
    r = run(
        ["omarchy-theme-set-templates"],
        timeout=30,
        env=omarchy_env(),
    )
    if r.returncode != 0:
        log.debug(
            "omarchy-theme-set-templates failed: %s",
            (r.stderr or r.stdout or "")[:200],
        )
        return False
    if not _install_generated_into_current():
        return False
    if mapping:
        _apply_hypr_borders(mapping)
    for cmd in _RETINT_COMMANDS:
        if have(cmd):
            run([cmd], timeout=20)
    return True


def refresh_browser_policy(ctx: WallpaperContext) -> bool:
    """Re-tint Chromium-family browser chrome from the freshly rendered theme.

    The retint above regenerates ``current/theme/chromium.theme``;
    omarchy's own helper turns that into the privileged managed policies
    (``/etc/*/policies/managed/color.json``, passwordless via the Omarchy
    sudoers rule) and refreshes running browsers via
    ``--refresh-platform-policy``. Omarchy owns those policies, so this is the
    only path that touches browser chrome — never BrowserPolicyOp.

    Soft-fails when the helper is missing or exits non-zero (e.g. no browser
    installed, or a non-stock install without the sudoers grant).
    """
    if not have("omarchy-theme-set-browser"):
        return False
    r = run(["omarchy-theme-set-browser"], timeout=30, env=omarchy_env())
    if r.returncode != 0:
        debug_op(
            "omarchy",
            "omarchy-theme-set-browser failed: "
            f"{(r.stderr or r.stdout or '').strip()[:200]}",
            ctx,
        )
        return False
    return True


_OPENCODE_APPLY_GRACE_S = 1.2


def _opencode_themes_dir() -> Path:
    """~/.config/opencode/themes with the plugin's env fallback semantics.

    Mirrors themesDir() in omarchy's omarchy-theme TUI plugin (and the
    ``${VAR:-...}`` defaults in omarchy-theme-set-opencode): truthy
    OPENCODE_CONFIG_DIR wins, else XDG_CONFIG_HOME, else ~/.config.
    """
    config = os.environ.get("OPENCODE_CONFIG_DIR")
    if not config:
        xdg = os.environ.get("XDG_CONFIG_HOME")
        base = Path(xdg) if xdg else home() / ".config"
        config = str(base / "opencode")
    return Path(config) / "themes"


def _opencode_theme_hash(text: str) -> str:
    """FNV-1a(32) over UTF-16 code units — omarchy's TUI plugin contentHash.

    The plugin installs each palette as ``omarchy-<hash>.json``; a missing
    hash file means no running session applied the current omarchy.json yet.
    Unit-wise (not byte-wise) hashing matches JS ``charCodeAt`` for non-ASCII.
    """
    data = text.encode("utf-16-le")
    h = 0x811C9DC5
    for i in range(0, len(data), 2):
        h ^= data[i] | (data[i + 1] << 8)
        h = (h * 0x01000193) & 0xFFFFFFFF
    return f"{h:08x}"


def _opencode_applied(themes_dir: Path, text: str) -> bool:
    expected = f"omarchy-{_opencode_theme_hash(text)}.json"
    try:
        return any(entry.name == expected for entry in themes_dir.glob("omarchy-*.json"))
    except OSError:
        return False


def _nudge_opencode_watchers(ctx: WallpaperContext) -> None:
    """Re-fire omarchy's theme watcher when no session applied the palette.

    opencode (Bun) occasionally misses the rename event behind
    omarchy-theme-set-opencode's atomic replace, leaving running sessions on
    the previous palette until the next change. Rewriting the same bytes is
    another plain fs event: every watcher re-applies, installs its
    content-hashed copy and prunes stale ones. No signals involved.
    """
    themes_dir = _opencode_themes_dir()
    path = themes_dir / "omarchy.json"
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return
    if _opencode_applied(themes_dir, text):
        return
    tmp = themes_dir / f".omarchy.json.nudge-{os.getpid()}"
    try:
        tmp.write_text(text, encoding="utf-8")
        os.replace(tmp, path)
    except OSError as e:
        debug_op("omarchy", f"opencode watcher nudge failed: {e}", ctx)
        try:
            tmp.unlink(missing_ok=True)
        except OSError:
            pass


def sync_opencode_theme(ctx: WallpaperContext) -> bool:
    """Refresh opencode colors from the freshly rendered theme.

    The retint regenerates ``current/theme/opencode.json``;
    omarchy-theme-set-opencode copies it to
    ``~/.config/opencode/themes/omarchy.json`` where omarchy's own TUI plugin
    watches it and retints running sessions. Called without ``--activate``:
    plugin installation and the tui.json theme selection stay omarchy
    theme-set territory (and _heal_opencode stays authoritative for
    de-theming).

    While opencode is running, the plugin's apply is verified via its
    content-hashed install; a missed fs event gets one same-bytes rewrite to
    re-fire the watchers.
    """
    if not have("omarchy-theme-set-opencode"):
        return False
    r = run(["omarchy-theme-set-opencode"], timeout=15, env=omarchy_env())
    if r.returncode != 0:
        debug_op(
            "omarchy",
            "omarchy-theme-set-opencode failed: "
            f"{(r.stderr or r.stdout or '').strip()[:200]}",
            ctx,
        )
        return False
    if not pgrep_exact("opencode"):
        return True
    # The watcher debounces 250ms and installs asynchronously; give it a beat
    # before judging whether the palette reached the running session(s).
    time.sleep(_OPENCODE_APPLY_GRACE_S)
    _nudge_opencode_watchers(ctx)
    time.sleep(_OPENCODE_APPLY_GRACE_S)
    themes_dir = _opencode_themes_dir()
    try:
        text = (themes_dir / "omarchy.json").read_text(encoding="utf-8")
    except OSError:
        return True
    if _opencode_applied(themes_dir, text):
        debug_op("omarchy", "opencode session(s) applied the palette", ctx)
    else:
        # Sessions may legitimately opt out (theme != omarchy*) — debug only.
        debug_op("omarchy", "no omarchy-<hash> install after sync/nudge", ctx)
    return True


class OmarchyThemeOp:
    name = "omarchy"

    def enabled(self, ctx: WallpaperContext) -> bool:
        if not ctx.ops.enable_omarchy:
            return False
        if not omarchy_available():
            return False
        return is_dynamic_theme_active(
            getattr(ctx.ops, "omarchy_theme_slug", THEME_SLUG)
        )

    def _heal_opencode(self, ctx: WallpaperContext) -> None:
        """Undo any stray wallust opencode theming (belt and braces).

        Long-running opencode sessions can still carry the removed
        wallust-hot-reload plugin, and older wallust configs had a hook that
        flipped tui.json back to theme "wallust" on every wallust run. Fix
        the registration whenever a wallpaper change touches the theme.
        """
        try:
            tui_path = home() / ".config" / "opencode" / "tui.json"
            if not tui_path.is_file():
                return
            import json

            tui = json.loads(tui_path.read_text(encoding="utf-8"))
            if not isinstance(tui, dict):
                return
            plugins = tui.get("plugin")
            listed = isinstance(plugins, list) and any(
                "wallust-hot-reload" in str(p) for p in plugins
            )
            if tui.get("theme") != "wallust" and not listed:
                return
        except (OSError, ValueError):
            return

        from wallpaperctl.setup.opencode_bootstrap import remove_opencode_plugin

        debug_op(self.name, "healing stray wallust opencode theming", ctx)
        remove_opencode_plugin()
        for stale in (
            home() / ".config" / "opencode" / "themes" / "wallust.json",
            *sorted((home() / ".config" / "opencode" / "themes").glob("wallust-hot-*.json")),
        ):
            try:
                stale.unlink()
            except OSError:
                pass

    def run(self, ctx: WallpaperContext) -> bool:
        slug = getattr(ctx.ops, "omarchy_theme_slug", THEME_SLUG)
        theme_dir = user_theme_dir(slug)
        debug_op(self.name, f"updating dynamic theme at {theme_dir}", ctx)

        colors = load_colors_json()
        if not colors:
            debug_op(self.name, "no ~/.cache/wal/colors.json (wallust op failed?)", ctx)
            return False

        strategy = (
            getattr(ctx.ops, "omarchy_accent_strategy", None)
            or getattr(ctx.ops, "rgb_color_strategy", "warmest")
            or "warmest"
        )
        mapping = build_colors_mapping(colors, accent_strategy=strategy)
        rendered = render_colors_toml(mapping)
        colors_file = theme_dir / "colors.toml"
        previous = _read_text(colors_file)
        write_colors_toml(theme_dir, mapping)
        debug_op(self.name, f"wrote {colors_file}", ctx)

        image = ctx.image_path
        if image is None or not image.is_file():
            debug_op(self.name, "no still image for theme media sync", ctx)
            return False
        sync_theme_media(
            theme_dir,
            image,
            video_path=ctx.path if ctx.is_animated else None,
        )

        self._heal_opencode(ctx)

        palette_changed = previous is None or previous != rendered

        if not getattr(ctx.ops, "omarchy_refresh_apps", True):
            debug_op(
                self.name,
                "omarchy_refresh_apps disabled: colors.toml staged only",
                ctx,
            )
        elif (
            getattr(ctx.ops, "omarchy_skip_unchanged", True)
            and not palette_changed
        ):
            debug_op(self.name, "palette unchanged; skipping app retint", ctx)
        else:
            from wallpaperctl.omarchy_watch import (
                restore_monitor_transforms,
                snapshot_monitor_transforms,
                suppress_layout_rebind,
            )

            # If Hyprland still auto-reloads for any other reason, put the
            # runtime transform back. Do not leave monitors.lua's landscape.
            transforms = snapshot_monitor_transforms()
            suppress_layout_rebind(8.0)
            if retint_without_compositor_reload(theme_dir, slug, mapping):
                debug_op(self.name, "kitty/hypr retinted from wallust palette", ctx)
                if getattr(ctx.ops, "omarchy_refresh_opencode", True):
                    if sync_opencode_theme(ctx):
                        debug_op(
                            self.name,
                            "opencode theme synced (omarchy-theme-set-opencode)",
                            ctx,
                        )
                else:
                    debug_op(
                        self.name,
                        "omarchy_refresh_opencode disabled; opencode theme untouched",
                        ctx,
                    )
                if getattr(ctx.ops, "omarchy_refresh_browser", True):
                    if refresh_browser_policy(ctx):
                        debug_op(
                            self.name,
                            "browser chrome re-tinted (omarchy-theme-set-browser)",
                            ctx,
                        )
                else:
                    debug_op(
                        self.name,
                        "omarchy_refresh_browser disabled; browser policy untouched",
                        ctx,
                    )
            else:
                debug_op(
                    self.name,
                    "live retint skipped (no omarchy-theme-set-templates?)",
                    ctx,
                )
            restore_monitor_transforms(transforms)

        if palette_changed:
            current, _ = _current_theme_dirs()
            colors = current / "colors.toml"
            shell = current / "shell.toml"
            apply_shell_theme_live(
                colors if colors.is_file() else colors_file,
                shell if shell.is_file() else None,
            )
        return True


def _read_text(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return None


def fallback_palette() -> dict:
    """Neutral dark palette for first-time bootstrap before any wallust run."""
    return {
        "special": {
            "background": "#101418",
            "foreground": "#c8ccd4",
            "cursor": "#c8ccd4",
        },
        "colors": {
            "color0": "#101418",
            "color1": "#cc6666",
            "color2": "#b5bd68",
            "color3": "#f0c674",
            "color4": "#81a2be",
            "color5": "#b294bb",
            "color6": "#8abeb7",
            "color7": "#c8ccd4",
            "color8": "#5c6370",
            "color9": "#de6e5c",
            "color10": "#98c379",
            "color11": "#e5c07b",
            "color12": "#61afef",
            "color13": "#c678dd",
            "color14": "#56b6c2",
            "color15": "#e6e6e6",
        },
    }


def ensure_theme_skeleton(
    theme_dir: Path | None = None,
    *,
    accent_strategy: str = "warmest",
) -> bool:
    """Create the dynamic theme skeleton if it does not exist yet (setup path)."""
    theme_dir = theme_dir or user_theme_dir()
    colors_file = theme_dir / "colors.toml"
    if colors_file.is_file():
        return False

    colors = load_colors_json()
    if not colors:
        wal_colors = home() / ".cache" / "wal" / "colors"
        if wal_colors.is_file():
            lines = [
                line.strip()
                for line in wal_colors.read_text(encoding="utf-8", errors="replace").splitlines()
                if line.strip()
            ]
            if len(lines) >= 16:
                colors = {
                    "special": {
                        "background": lines[0],
                        "foreground": lines[7],
                        "cursor": lines[15],
                    },
                    "colors": {f"color{i}": lines[i] for i in range(16)},
                }
    if not colors:
        colors = fallback_palette()

    write_colors_toml(theme_dir, build_colors_mapping(colors, accent_strategy=accent_strategy))
    (theme_dir / "backgrounds").mkdir(parents=True, exist_ok=True)

    current = home() / ".wallpaper"
    seeded = False
    try:
        if current.is_file():
            wallpaper = Path(current.read_text(encoding="utf-8").strip())
            if wallpaper.is_file():
                sync_theme_media(theme_dir, wallpaper)
                seeded = True
    except OSError as e:
        log.debug("omarchy theme: could not seed backgrounds: %s", e)

    # The omarchy theme switcher only lists themes that ship a preview image.
    if not seeded and not (theme_dir / "preview.png").is_file():
        mapping = build_colors_mapping(colors, accent_strategy=accent_strategy)
        write_palette_preview(theme_dir, mapping)
    return True
