-- awesome-colors.lua — wallust template for AwesomeWM
--
-- Template location: ~/.config/wallust/templates/awesome-colors.lua
-- Output location:   ~/.cache/wal/awesome-colors.lua   (set in wallust.toml)
--
-- This file uses wallust's "new engine" ({{variable}} syntax).
-- Read by themes/<name>/theme.lua at AwesomeWM startup.
--
-- Do not edit the generated output at ~/.cache/wal/awesome-colors.lua —

-- Generated by wallust — do not edit the output file manually
return {
    wallpaper   = "{{wallpaper}}",
    background  = "{{background}}",
    foreground  = "{{foreground}}",
    cursor      = "{{cursor}}",
    color0      = "{{color0}}",
    color1      = "{{color1}}",
    color2      = "{{color2}}",
    color3      = "{{color3}}",
    color4      = "{{color4}}",
    color5      = "{{color5}}",
    color6      = "{{color6}}",
    color7      = "{{color7}}",
    color8      = "{{color8}}",
    color9      = "{{color9}}",
    color10     = "{{color10}}",
    color11     = "{{color11}}",
    color12     = "{{color12}}",
    color13     = "{{color13}}",
    color14     = "{{color14}}",
    color15     = "{{color15}}",
}
