# AUTO-GENERATED by wallust: Registers 'wallust' custom style for xonsh syntax highlighting
# Loaded early via ~/.xonshrc – do not edit manually; regenerates on wallpaper change

from xonsh.tools import register_custom_style

# Wallust palette interpolated as hex colors
wallust_colors = {
    'background': '{{ background }}',
    'foreground': '{{ foreground }}',
    'color0': '{{ color0 }}', 'color1': '{{ color1 }}', 'color2': '{{ color2 }}',
    'color3': '{{ color3 }}', 'color4': '{{ color4 }}', 'color5': '{{ color5 }}',
    'color6': '{{ color6 }}', 'color7': '{{ color7 }}',
    'color8': '{{ color8 }}', 'color9': '{{ color9 }}', 'color10': '{{ color10 }}',
    'color11': '{{ color11 }}', 'color12': '{{ color12 }}', 'color13': '{{ color13 }}',
    'color14': '{{ color14 }}', 'color15': '{{ color15 }}',
}

# Custom token mappings (adjust as needed; based on common pywal/wallust preferences)
# These map Pygments tokens to wallust colors for syntax highlighting
wallust_style = {
    # Background and global foreground
    'TOKEN.Background': wallust_colors['background'],
    'TOKEN.Foreground': wallust_colors['foreground'],

    # Core syntax elements
    'TOKEN.Keyword': wallust_colors['color4'],      # Blue for keywords (e.g., def, if)
    'TOKEN.Name.Function': wallust_colors['color2'], # Green for function names
    'TOKEN.Name.Class': wallust_colors['color3'],   # Yellow for classes
    'TOKEN.Name.Variable': wallust_colors['color6'], # Cyan for variables
    'TOKEN.String': wallust_colors['color6'],       # Cyan for strings
    'TOKEN.Comment': wallust_colors['color8'],      # Dim for comments (bright black)
    'TOKEN.Number': wallust_colors['color1'],       # Red for numbers
    'TOKEN.Operator': wallust_colors['color5'],     # Magenta for operators

    # Errors and emphasis
    'TOKEN.Error': wallust_colors['color9'],        # Bright red for errors
    'TOKEN.Name.Exception': wallust_colors['color1'], # Red for exceptions

    # Prompt-related tokens (for $PROMPT integration)
    'TOKEN.Username': wallust_colors['color12'],    # Bright blue for user
    'TOKEN.Hostname': wallust_colors['color14'],    # Bright cyan for host
    'TOKEN.Cwd': wallust_colors['color4'],          # Blue for current directory
}

# Register the style (base='monokai' provides fallbacks for undefined tokens)
register_custom_style('wallust', wallust_style, base='monokai')

# Activate the style
$XONSH_COLOR_STYLE = 'wallust'
