/* Dynamic Cinnamon theme based on official Cinnamon theme structure */
/* Generated by wallpaperctl */
/* Colors: bg=#$color0, fg=#$color7, accent=#$color4, hover=#$color2 */

/* Import base Cinnamon theme for compatibility */
@import url("resource:///org/cinnamon/theme/cinnamon.css");

/* === STAGE AND BASIC ELEMENTS === */
stage {
    color: #$color7;
}

/* === PANEL === */
#panel {
    font-weight: bold;
    /* sets the height of horizontal panels */
    height: 40px;
    /* sets the width of vertical panels */  
    width: 32px;
    color: #$color7;
    /* Use Cinnamon-specific background gradient syntax instead of CSS gradients */
    background-gradient-direction: vertical;
    background-gradient-start: rgba($bg_rgb, 1.0);
    background-gradient-end: rgba($accent_rgb, 0.8);
}

#panel:highlight {
    border-image: none;
    background-color: rgba($accent_rgb, 0.8);
}

#panelLeft {
    spacing: 4px;
}

#panelLeft:ltr {
    padding-right: 4px;
}

#panelLeft:rtl {
    padding-left: 4px;
}

#panelRight:ltr {
    padding-left: 4px;
    spacing: 0;
}

#panelRight:rtl {
    padding-right: 4px;
    spacing: 0;
}

#panelCenter {
    spacing: 4px;
}

/* === POPUP MENUS (Context Menus, Right-click menus) === */
.popup-menu-content {
    padding: 6px;
    background-color: #$color0;
    border-radius: 16px;
    border: 1px solid rgba($accent_rgb, 0.5);
    box-shadow: 0 0 6px rgba(0, 0, 0, 0.5);
}

.popup-menu-item {
    font-weight: normal;
    spacing: 6px;
    transition-duration: 100ms;
    padding: 8px 12px;
    margin: 0 4px;
    border-radius: 8px;
    color: #$color7;
    background-color: transparent;
}

.popup-menu-item:active {
    background-color: rgba($accent_rgb, 0.3);
    color: #$color7;
}

.popup-menu-item:insensitive {
    color: rgba($color7_rgb, 0.4);
    background: none;
}

/* Menu icons and arrows */
.popup-menu-arrow,
.popup-menu-icon {
    icon-size: 16px;
    color: #$color7;
}

/* Submenu styling */
.popup-sub-menu {
    border-radius: 9px;
    margin: 0 4px;
    margin-bottom: 6px;
    border: 1px solid rgba(0, 0, 0, 0.1);
}

.popup-sub-menu .popup-menu-item {
    border-radius: 0;
    background-color: rgba($bg_rgb, 0.8);
    margin: 0;
    padding: 8px 0 8px 12px;
}

.popup-sub-menu .popup-menu-item:active {
    background-color: rgba($accent_rgb, 0.2);
}

.popup-sub-menu .popup-menu-item:first-child {
    border-radius: 8px 8px 0 0;
}

.popup-sub-menu .popup-menu-item:last-child {
    border-radius: 0 0 8px 8px;
}

.popup-sub-menu .popup-menu-item:only-child,
.popup-sub-menu .popup-menu-item:first-child:last-child {
    border-radius: 8px;
}

/* Menu separators */
.popup-separator-menu-item {
    -gradient-height: 1px;
    -gradient-start: rgba($accent_rgb, 0.3);
    -gradient-end: rgba($accent_rgb, 0.3);
    -margin-horizontal: 0;
    height: 1px;
}

/* === START/APPLICATION MENU === */
.menu {
    min-width: 15em;
    color: #$color7;
    padding: 6px;
}

.menu-favorites-box {
    padding: 9px;
    background-color: rgba($bg_rgb, 0.6);
    border: 1px solid rgba(0, 0, 0, 0.1);
    border-radius: 8px;
}

.menu-favorites-button {
    padding: 9px;
    border-radius: 8px;
    spacing: 4px;
}

.menu-favorites-button:hover {
    background-color: rgba($hover_rgb, 0.3);
}

.menu-categories-box {
    padding: 9px 24px;
}

.menu-applications-box {
    padding: 9px;
}

.menu-applications-inner-box:ltr {
    padding-left: 24px;
}

.menu-applications-inner-box:rtl {
    padding-right: 24px;
}

/* Application buttons */
.menu-application-button {
    padding: 6px;
    spacing: 4px;
    border-radius: 8px;
    color: #$color7;
    background-color: transparent;
}

.menu-application-button:highlighted {
    font-weight: bold;
}

.menu-application-button-selected {
    padding: 6px;
    spacing: 4px;
    border-radius: 8px;
    background-color: rgba($accent_rgb, 0.3);
    color: #$color7;
}

.menu-application-button-selected:highlighted {
    font-weight: bold;
}

.menu-application-button-label {
    padding: 0;
    color: #$color7;
}

/* Category buttons */
.menu-category-button {
    padding: 6px;
    spacing: 4px;
    border-radius: 8px;
    color: #$color7;
    background-color: transparent;
}

.menu-category-button:hover {
    background-color: rgba($hover_rgb, 0.2);
}

.menu-category-button-selected {
    padding: 6px;
    spacing: 4px;
    border-radius: 8px;
    background-color: rgba($accent_rgb, 0.3);
    color: #$color7;
}

.menu-category-button-greyed {
    padding: 6px;
    spacing: 4px;
    border-radius: 8px;
    color: rgba($color7_rgb, 0.4);
    font-style: italic;
}

.menu-category-button-greyed StIcon {
    opacity: 0.5;
}

.menu-category-button-label {
    padding: 0;
    color: #$color7;
}

/* Search box */
.menu-search-box {
    padding: 0 0 6px 9px;
}

#menu-search-entry {
    min-height: 22px;
    border-radius: 8px;
    padding: 6px 9px;
    border: 1px solid rgba($accent_rgb, 0.5);
    caret-color: #$color7;
    selected-color: black;
    selection-background-color: #$color4;
    caret-size: 1px;
    background-color: rgba($bg_rgb, 0.8);
    color: #$color7;
}

#menu-search-entry:focus {
    border-color: #$color4;
    box-shadow: 0 0 3px rgba($accent_rgb, 0.5);
}

.menu-search-entry-icon {
    icon-size: 16px;
    color: #$color7;
}

/* Selected app info */
.menu-selected-app-box {
    padding-right: 24px;
    padding-left: 24px;
    text-align: right;
}

.menu-selected-app-title {
    font-weight: 700;
    color: #$color7;
}

.menu-selected-app-description {
    color: rgba($color7_rgb, 0.4);
}

/* === PANEL BUTTONS AND APPLETS === */
.panel-button,
.applet-button {
    background-color: transparent;
    color: #$color7;
    border-radius: 4px;
    padding: 4px 8px;
    transition: all 0.2s ease;
}

.panel-button:hover,
.applet-button:hover {
    background-color: rgba($hover_rgb, 0.3);
    color: #$color7;
}

.panel-button:active,
.applet-button:active {
    background-color: rgba($accent_rgb, 0.4);
}

/* === WINDOW LIST === */
.window-list-item-box {
    background: linear-gradient(to bottom,
                rgba($accent_rgb, 0.3),
                rgba($bg_rgb, 0.8),
                rgba($accent_rgb, 0.2));
    color: #$color7;
    border: 1px solid rgba($accent_rgb, 0.4);
    border-radius: 4px;
    margin: 2px;
    padding: 4px 8px;
    transition: all 0.2s ease;
}

.window-list-item-box:hover {
    background-color: rgba($hover_rgb, 0.4);
}

.window-list-item-box.active {
    background-color: rgba($accent_rgb, 0.6);
    color: #$color7;
}

/* === GROUPED WINDOW LIST (TASK LIST WIDGET) === */
.grouped-window-list-item-box {
    padding: 0 6px;
    color: #$color7;
    border-radius: 4px;
    transition: all 0.2s ease;
}

.grouped-window-list-item-box.top,
.grouped-window-list-item-box.bottom {
    border-bottom-width: 2px;
    border-bottom-color: rgba($accent_rgb, 0.6);
}

.grouped-window-list-item-box.right {
    padding-left: 0;
    padding-right: 0;
    border-right-width: 2px;
    border-right-color: rgba($accent_rgb, 0.6);
}

.grouped-window-list-item-box.right StBin {
    padding-right: 0;
}

.grouped-window-list-item-box.left {
    padding-left: 0;
    padding-right: 0;
    border-left-width: 2px;
    border-left-color: rgba($accent_rgb, 0.6);
}

.grouped-window-list-item-box.left StBin {
    padding-left: 1px;
}

.grouped-window-list-item-box:hover {
    background-color: rgba($hover_rgb, 0.4);
    color: #$color7;
}

.grouped-window-list-item-box:focus {
    background-color: rgba($accent_rgb, 0.3);
    color: #$color7;
}

.grouped-window-list-item-box:active {
    border-color: rgba($accent_rgb, 0.8);
    background-color: rgba($accent_rgb, 0.5);
    color: #$color7;
}

.grouped-window-list-item-demands-attention {
    background-color: rgba($hover_rgb, 0.8);
    border-color: rgba($hover_rgb, 0.9);
}

.grouped-window-list-thumbnail-alert {
    background: rgba($hover_rgb, 0.3);
}

.grouped-window-list-thumbnail-menu {
    border: 1px solid rgba($accent_rgb, 0.5);
    margin: 6px;
    background-color: rgba($bg_rgb, 0.95);
    border-radius: 8px;
    box-shadow: 0 0 6px 0 rgba(0, 0, 0, 0.5);
}

.grouped-window-list-thumbnail-menu > StBoxLayout {
    padding: 4px;
}

.grouped-window-list-thumbnail-menu .item-box {
    padding: 10px;
    spacing: 4px;
    border-radius: 0;
    color: #$color7;
}

.grouped-window-list-thumbnail-menu .item-box:first-child {
    border-radius: 8px 0 0 8px;
}

.grouped-window-list-thumbnail-menu .item-box:last-child {
    border-radius: 0 8px 8px 0;
}

.grouped-window-list-thumbnail-menu .item-box:outlined {
    border: 2px solid rgba($accent_rgb, 0.7);
}

.grouped-window-list-thumbnail-menu .item-box:outlined:first-child {
    border-radius: 8px 0 0 8px;
}

.grouped-window-list-thumbnail-menu .item-box:outlined:last-child {
    border-radius: 0 8px 8px 0;
}

.grouped-window-list-thumbnail-menu .item-box:selected {
    background-color: rgba($accent_rgb, 0.4);
    color: #$color7;
}

.grouped-window-list-thumbnail-menu .item-box:selected:only-child,
.grouped-window-list-thumbnail-menu .item-box:selected:first-child:last-child {
    border-radius: 8px;
}

.grouped-window-list-thumbnail-menu .item-box:selected:first-child {
    border-radius: 8px 0 0 8px;
}

.grouped-window-list-thumbnail-menu .item-box:selected:last-child {
    border-radius: 0 8px 8px 0;
}

.grouped-window-list-thumbnail-menu .separator {
    width: 1px;
    background-color: rgba($accent_rgb, 0.3);
}

.grouped-window-list-button-label {
    padding-left: 4px;
    color: #$color7;
}

.grouped-window-list-number-label {
    font-size: 0.8em;
    z-index: 99;
    color: #$color7;
}

.grouped-window-list-badge {
    border-radius: 9999px;
    background-color: rgba($bg_rgb, 0.9);
    color: #$color7;
}

/* === WORKSPACE SWITCHER === */
.workspace-switcher {
    background: linear-gradient(to right,
                rgba($accent_rgb, 0.4),
                rgba($bg_rgb, 0.9),
                rgba($accent_rgb, 0.4));
    border: 1px solid rgba($accent_rgb, 0.5);
    border-radius: 6px;
    padding: 4px;
    box-shadow: 0 2px 4px rgba($accent_rgb, 0.3);
}

.workspace-button {
    background-color: transparent;
    color: #$color7;
    border-radius: 4px;
    margin: 2px;
}

.workspace-button:hover {
    background-color: rgba($hover_rgb, 0.3);
}

.workspace-button.active {
    background-color: rgba($accent_rgb, 0.6);
    color: #$color7;
}

/* === CALENDAR === */
.calendar {
    background-color: #$color0;
    color: #$color7;
    border-radius: 8px;
    border: 1px solid rgba($accent_rgb, 0.5);
    padding: 6px;
}

.calendar-day {
    color: #$color7;
    border-radius: 4px;
    padding: 4px;
}

.calendar-day:hover {
    background-color: rgba($hover_rgb, 0.3);
}

.calendar-day.selected {
    background-color: rgba($accent_rgb, 0.6);
    color: #$color7;
}

/* === ALT-TAB SWITCHER === */
.switcher-list {
    background-color: rgba($bg_rgb, 0.95);
    border: 2px solid rgba($accent_rgb, 0.7);
    border-radius: 24px;
    box-shadow: 0 8px 30px rgba(0, 0, 0, 0.5);
    padding: 12px;
}

.switcher-item {
    color: #$color7;
    background-color: transparent;
    border-radius: 8px;
    padding: 8px;
}

.switcher-item:selected,
.switcher-item:hover {
    background-color: rgba($accent_rgb, 0.4);
    color: #$color7;
}

/* === TOOLTIPS === */
.tooltip {
    background-color: rgba($bg_rgb, 0.95);
    color: #$color7;
    border: 1px solid rgba($accent_rgb, 0.5);
    border-radius: 6px;
    padding: 8px 12px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
}

/* === NOTIFICATIONS === */
#notification {
    border-radius: 8px;
    background-color: rgba($bg_rgb, 0.95);
    color: #$color7;
    border: 1px solid rgba($accent_rgb, 0.5);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
    padding: 12px;
    spacing-rows: 10px;
    spacing-columns: 10px;
    margin-from-right-edge-of-screen: 20px;
    width: 34em;
    font-weight: normal;
    font-size: 12px;
}

#notification.multi-line-notification {
    padding-bottom: 12px;
    color: #$color7;
}

.notification-with-image {
    min-height: 159px;
    color: #$color7;
}

#notification-body {
    spacing: 6px;
}

#notification-actions {
    spacing: 10px;
}

.notification-button {
    border-radius: 4px;
    padding: 6px 12px;
    background-color: rgba($accent_rgb, 0.6);
    color: #$color7;
    border: 1px solid rgba($accent_rgb, 0.8);
}

.notification-button:focus {
    background-color: rgba($accent_rgb, 0.8);
    color: #$color7;
}

.notification-icon-button {
    border-radius: 4px;
    padding: 6px;
    background-color: rgba($accent_rgb, 0.6);
    border: 1px solid rgba($accent_rgb, 0.8);
}

.notification-icon-button:focus {
    background-color: rgba($accent_rgb, 0.8);
}

.notification-icon-button > StIcon {
    icon-size: 24px;
    color: #$color7;
}

#notification .url-highlighter {
    link-color: #$color4;
}

#notification StEntry {
    padding: 6px;
    border-radius: 4px;
    color: #$color7;
    border: 1px solid rgba($accent_rgb, 0.5);
    background-color: rgba($bg_rgb, 0.8);
}

#notification StEntry:focus {
    border: 1px solid rgba($accent_rgb, 0.8);
}

#notification .cinnamon-link {
    color: #$color4;
    text-decoration: underline;
}

/* === ICON COLORS === */
.applet-icon,
.panel-launcher .icon,
.panel-status-button .icon {
    color: #$color7;
}

.popup-menu-item .icon,
.menu-item .icon,
.menu .icon {
    color: #$color7;
}

.system-status-icon,
.panel-status-button {
    color: #$color7;
}

.window-list-item .icon,
.workspace-button .icon {
    color: #$color7;
}

/* Selected/active states use accent color */
.window-list-item.active .icon,
.workspace-button.active .icon,
*:selected .icon {
    color: #$color4;
}